//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHITIET_THAMQUAN
    {
        public string MA_DTQ { get; set; }
        public string MA_TOUR { get; set; }
        public Nullable<int> THOIGIAN { get; set; }
    
        public virtual DIEM_THAM_QUAN DIEM_THAM_QUAN { get; set; }
        public virtual TOUR TOUR { get; set; }
    }
}
