//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHUYEN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CHUYEN()
        {
            this.CT_PHIEU_DK = new HashSet<CT_PHIEU_DK>();
        }
    
        public string MA_CHUYEN { get; set; }
        public string TENCHUYEN { get; set; }
        public Nullable<System.DateTime> NGAYDI { get; set; }
        public string MA_TOUR { get; set; }
        public Nullable<double> GIA { get; set; }
        public string Anh { get; set; }
    
        public virtual TOUR TOUR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CT_PHIEU_DK> CT_PHIEU_DK { get; set; }
    }
}
