//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CT_DIEM_DUNG_CHAN
    {
        public string MA_NOIDI { get; set; }
        public string MA_NOIDEN { get; set; }
        public string MA_DDC { get; set; }
        public Nullable<System.DateTime> THOI_GIAN { get; set; }
    
        public virtual DIEM_DUNG_CHAN DIEM_DUNG_CHAN { get; set; }
        public virtual LO_TRINH LO_TRINH { get; set; }
    }
}
