//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CT_PHIEU_DK
    {
        public string MA_PHIEU { get; set; }
        public string MA_CHUYEN { get; set; }
        public Nullable<int> SO_NGUOI { get; set; }
    
        public virtual CHUYEN CHUYEN { get; set; }
        public virtual PHIEU_DK PHIEU_DK { get; set; }
    }
}
