//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DIEM_DUNG_CHAN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DIEM_DUNG_CHAN()
        {
            this.CT_DIEM_DUNG_CHAN = new HashSet<CT_DIEM_DUNG_CHAN>();
        }
    
        public string MA_DDC { get; set; }
        public string TEN_DDC { get; set; }
        public string THANH_PHO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CT_DIEM_DUNG_CHAN> CT_DIEM_DUNG_CHAN { get; set; }
    }
}
