//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DIEM_THAM_QUAN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DIEM_THAM_QUAN()
        {
            this.CHITIET_THAMQUAN = new HashSet<CHITIET_THAMQUAN>();
        }
    
        public string MA_DTQ { get; set; }
        public string TEN_DTQ { get; set; }
        public string NOIDUNG { get; set; }
        public string YNGHIA { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIET_THAMQUAN> CHITIET_THAMQUAN { get; set; }
    }
}
