//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HD_NV
    {
        public string MA_HD { get; set; }
        public string MANV_HDDL { get; set; }
        public string NOIDUNG_HD { get; set; }
    
        public virtual HOP_DONG HOP_DONG { get; set; }
        public virtual NV_HDDL NV_HDDL { get; set; }
    }
}
