//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOP_DONG
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HOP_DONG()
        {
            this.HD_NV = new HashSet<HD_NV>();
        }
    
        public string MA_HD { get; set; }
        public string NOIDUNG { get; set; }
        public Nullable<int> SO_NGAYDI { get; set; }
        public string NOI_DON { get; set; }
        public Nullable<System.DateTime> NGAYDI_HD { get; set; }
        public string MA_DOAN { get; set; }
        public string MA_TOUR { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HD_NV> HD_NV { get; set; }
        public virtual KHACH_DOAN KHACH_DOAN { get; set; }
        public virtual TOUR TOUR { get; set; }
    }
}
