//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NV_HDDL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NV_HDDL()
        {
            this.HD_NV = new HashSet<HD_NV>();
        }
    
        public string MANV_HDDL { get; set; }
        public string TEN_NV { get; set; }
        public Nullable<System.DateTime> NGAYSINH { get; set; }
        public string PHAI { get; set; }
        public string DIACHI { get; set; }
        public Nullable<int> DT { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HD_NV> HD_NV { get; set; }
    }
}
