//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace web.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class tourEntities : DbContext
    {
        public tourEntities()
            : base("name=tourEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CHITIET_THAMQUAN> CHITIET_THAMQUAN { get; set; }
        public virtual DbSet<CHUYEN> CHUYENs { get; set; }
        public virtual DbSet<CT_DIEM_DUNG_CHAN> CT_DIEM_DUNG_CHAN { get; set; }
        public virtual DbSet<CT_PHIEU_DK> CT_PHIEU_DK { get; set; }
        public virtual DbSet<DIEM_DUNG_CHAN> DIEM_DUNG_CHAN { get; set; }
        public virtual DbSet<DIEM_THAM_QUAN> DIEM_THAM_QUAN { get; set; }
        public virtual DbSet<HD_NV> HD_NV { get; set; }
        public virtual DbSet<HOP_DONG> HOP_DONG { get; set; }
        public virtual DbSet<KHACH_DOAN> KHACH_DOAN { get; set; }
        public virtual DbSet<KHACHHANG> KHACHHANGs { get; set; }
        public virtual DbSet<LO_TRINH> LO_TRINH { get; set; }
        public virtual DbSet<LOTRINH_TOUR> LOTRINH_TOUR { get; set; }
        public virtual DbSet<NHANVIEN> NHANVIENs { get; set; }
        public virtual DbSet<NV_HDDL> NV_HDDL { get; set; }
        public virtual DbSet<PHIEU_DK> PHIEU_DK { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TOUR> TOURs { get; set; }
    }
}
