//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TOUR
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TOUR()
        {
            this.CHITIET_THAMQUAN = new HashSet<CHITIET_THAMQUAN>();
            this.CHUYENs = new HashSet<CHUYEN>();
            this.HOP_DONG = new HashSet<HOP_DONG>();
        }
    
        public string MA_TOUR { get; set; }
        public string TEN_TOUR { get; set; }
        public string Anh { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public Nullable<int> SO_NGAY { get; set; }
        public Nullable<int> SO_DEM { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIET_THAMQUAN> CHITIET_THAMQUAN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHUYEN> CHUYENs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HOP_DONG> HOP_DONG { get; set; }
        public virtual LOTRINH_TOUR LOTRINH_TOUR { get; set; }
    }
}
